name: 'Docker Publish Beta'

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  publish:
    name: Docker Publish Beta
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: pre
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64,linux/arm/v7'
          push: true
          tags: |
            ttionya/vaultwarden-backup:${{ steps.pre.outputs.tag }}
            ttionya/bitwardenrs-backup:${{ steps.pre.outputs.tag }}
      -
        name: Build and push (for arm/v6)
        uses: docker/build-push-action@v2
        with:
          context: '.'
          file: './Dockerfile.alpine'
          platforms: 'linux/arm/v6'
          push: true
          tags: |
            ttionya/vaultwarden-backup:${{ steps.pre.outputs.tag }}
            ttionya/bitwardenrs-backup:${{ steps.pre.outputs.tag }}
